[package]
name = "diagonal_difference"
version = "0.1.0"
authors = ["José Viteri <josevns95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.22.0"
ndarray = "0.13.1"
